apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  labels:
    {{- include "helm-data-tank.labels" . | nindent 4 }}
data:
{{- with .Values.configmap.data }}
  {{- toYaml . | nindent 2 }}
{{- end }}
