apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.secret.name}}
  labels:
    {{- include "helm-data-tank.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.secret.data}}
    {{- toYaml . | nindent 2  }}
  {{- end}}